version: 2.1
jobs:
  say-hello:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  say-test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "Say test"
          command: "echo Test!"
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
   test-workflow:
     jobs:
      - say-test
